def manejo_errores(exception):
    print(exception)